In [1]:
import tensorflow as tf
import numpy as np
import os,glob,cv2
import sys,argparse
import matplotlib.pyplot as plt

from sklearn import metrics
from sklearn.metrics import roc_auc_score

image_size=128
num_channels=3
match_bad=0
match_good=0
bad_scores0=[]
bad_scores1=[]

/home/lishuai/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
/home/lishuai/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [ ]:
for img_path in glob.glob("./test/*.jpg"):
    images=[]
    
    image=cv2.imread(img_path)
    image=cv2.resize(image,(image_size,image_size),0,0,cv2.INTER_LINEAR)
    images.append(image)
    
    images=np.array(images,dtype=np.uint8)
    images=images.astype('float32')
    images=np.multiply(images,1.0/255.0)
    
    x_batch=images.reshape(1,image_size,image_size,num_channels)
    
    sess=tf.Session()

    saver=tf.train.import_meta_graph('./good-bad-model.meta')
    saver.restore(sess,tf.train.latest_checkpoint('./'))
    
    graph=tf.get_default_graph()
    
    y_pred=graph.get_tensor_by_name('y_pred:0')
    x=graph.get_tensor_by_name('x:0')
    
    y_true=graph.get_tensor_by_name('y_true:0')
    y_test_images=np.zeros((1,2))
    
    feed_dict_testing={x:x_batch,y_true:y_test_images}
    result=sess.run(y_pred,feed_dict=feed_dict_testing)
    
    print('Models output\n',result)
    bad_scores0.append(result[0][0])
#     index=result.argmax(axis=1)
#     if index[0]==0:
#         match_bad+=1
# print('match_bad is %d images'%match_bad)

INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.00969777 0.99030226]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.30588058 0.6941194 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.18672596 0.8132741 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.20223358 0.7977664 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.039043 0.960957]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.2986058 0.7013942]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.06398346 0.9360165 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.01928233 0.9807177 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.48078173 0.51921827]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.11703856 0.88296145]]
INFO:t

INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.08123202 0.918768  ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.03011246 0.96988755]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.04484513 0.95515484]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.04372532 0.9562747 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.01846387 0.9815361 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.00804266 0.9919573 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.03238482 0.9676151 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.01328232 0.9867177 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.00302744 0.99697256]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.00550874 0.9944912 ]]


Models output
 [[0.08192819 0.91807187]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.00933469 0.9906653 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.27104044 0.72895956]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.00141612 0.9985839 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.5853351 0.4146649]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.01604533 0.98395467]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.01465618 0.98534375]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.0012287  0.99877125]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[9.712110e-04 9.990288e-01]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.11963159 0.8803684 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-mode

Models output
 [[0.01360038 0.98639965]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.00353677 0.99646324]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.34521443 0.6547855 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.02512182 0.97487813]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.1951099 0.8048901]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.07765247 0.92234755]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.11724982 0.88275015]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.02929921 0.9707008 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.01375713 0.9862429 ]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Models output
 [[0.5668508  0.43314928]]
INFO:tensorflow:Restoring parameters from ./good-bad-model
Mo

In [3]:
for img_path in glob.glob("./test/good/*.jpg"):
    images=[]
    image=cv2.imread(img_path)
    image=cv2.resize(image,(image_size,image_size),0,0,cv2.INTER_LINEAR)
    images.append(image)

    
    images=np.array(images,dtype=np.uint8)
    images=images.astype('float32')
    images=np.multiply(images,1.0/255.0)
    
    x_batch=images.reshape(1,image_size,image_size,num_channels)
    sess=tf.Session()
    
    #saver=tf.train.import_meta_graph('./weights3/good-bad-model.meta')
    #saver.restore(sess,tf.train.latest_checkpoint('./weights3'))
    
    saver=tf.train.import_meta_graph('./good-bad-model.meta')
    saver.restore(sess,tf.train.latest_checkpoint('./'))
    
    graph=tf.get_default_graph()
    y_pred=graph.get_tensor_by_name('y_pred:0')
    x=graph.get_tensor_by_name('x:0')
    
    y_true=graph.get_tensor_by_name('y_true:0')
    y_test_images=np.zeros((1,2))
    
    feed_dict_testing={x:x_batch,y_true:y_test_images}
    result=sess.run(y_pred,feed_dict=feed_dict_testing)
    
    print(result,result.shape,result[0][0])
    bad_scores1.append(result[0][0])
    print(result.argmax(axis=1))
    print(result.argmax(axis=1))
    index=result.argmax(axis=1)
    if index[0]==1:
        match_good+=1
print('match good is %d images'%match_good)

INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.48538435  0.51461565]] (1, 2) 0.485384
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.50265419  0.49734575]] (1, 2) 0.502654
[0]
[0]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.40652046  0.59347957]] (1, 2) 0.40652
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.41992849  0.58007151]] (1, 2) 0.419928
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.41435948  0.58564049]] (1, 2) 0.414359
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.41514555  0.58485442]] (1, 2) 0.415146
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.40476903  0.595231  ]] (1, 2) 0.404769
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.40783808  0.59216189]] (1, 2) 0.407838
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.36089864  0.63910139]] (1, 2) 0.360899
[1]
[1]
IN

INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.58183962  0.41816029]] (1, 2) 0.58184
[0]
[0]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.4073824   0.59261757]] (1, 2) 0.407382
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.42674151  0.57325846]] (1, 2) 0.426742
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.43421212  0.56578785]] (1, 2) 0.434212
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.61305797  0.38694203]] (1, 2) 0.613058
[0]
[0]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.35916141  0.64083862]] (1, 2) 0.359161
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.47379428  0.52620578]] (1, 2) 0.473794
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.46353343  0.53646654]] (1, 2) 0.463533
[1]
[1]
INFO:tensorflow:Restoring parameters from ./good-bad-model
[[ 0.55167741  0.44832259]] (1, 2) 0.551677
[0]
[0]
IN

In [4]:
from sklearn.metrics import average_precision_score
from sklearn.metrics import precision_recall_curve
# Generate the appropriate format for evaluation 
y_bad=np.ones([30])
y_good=np.ones([116])
y_bad-=1
print(y_bad,y_bad.shape)
print(y_good,y_good.shape)
y_label=np.concatenate((y_bad,y_good),axis=0)
predict_scores=np.concatenate((bad_scores0,bad_scores1),axis=0)


average_precision = average_precision_score(y_label, predict_scores)
print('Average precision-recall score: {0:0.2f}'.format(average_precision))
precision, recall, _ = precision_recall_curve(y_label, predict_scores)
plt.step(recall, precision, color='b', alpha=0.2,where='post')
plt.fill_between(recall, precision, step='post', alpha=0.2,color='b')
plt.xlabel('Recall')
plt.ylabel('Precision')
plt.ylim([0.0, 1.05])
plt.xlim([0.0, 1.0])
plt.title('2-class Precision-Recall curve: AP={0:0.2f}'.format(average_precision))
plt.savefig('Precision_Recall')
plt.show()


#Draw the ROC curve and calculate the AUC for evaluating the model
# fpr,tpr,thresholds=metrics.roc_curve(y_label,predict_scores,pos_label=0)
# plt.plot(fpr,tpr)
# plt.xlabel('False Positive Rate')
# plt.ylabel('True Positive Rate')
# plt.title('ROC Curve')
# plt.savefig('Results')
# plt.show()

# AUC=roc_auc_score(y_label,predict_scores)
# print(AUC)


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.] (30,)
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.] (116,)


ValueError: Found input variables with inconsistent numbers of samples: [146, 30]